# https://neovide.dev/configuration.html
fork = true
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false
linespace=0

[font]
normal = ["JetBrainsMono Nerd Font"]
# normal = ["IosevkaTerm Nerd Font"]
size = 14

[box-drawing]
mode = "native"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes
