###
# Description:
# - Define bash session Aliases in yaml key/value format
# - These will be loaded into your bash session via ./init/load_aliases.sh
###

grabpage: 'wget -p -k -E -H'

bot: "ollama run $ACTIVE_BOT"
bat: "bat -p"
cat: "bat -p"
# fzf: "fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
b: ${BROWSER}
e: nvim
eg: "neovide"
r: "source ~/.bashrc"
ff: "fastfetch"

lsd: "lsd --hyperlink=auto"
ls: "lsd"
l: "ls"
ll: "ls -la"

lgit: lazygit
ldocker: lazydocker
ljournal: lazyjournal
lsql: lazysql

allow: "sudo chmod +x"
own: "sudo chown"

yt: "invidious_instance='https://vid.puffyan.us' ytfzf -t"
tree: "tree -CAS --hyperlink"

vmon: "sudo systemctl start libvirtd.service qemu-kvm.service virtlockd.service virtlogd.service"
vmoff: "sudo systemctl stop libvirtd.service qemu-kvm.service virtlockd.service virtlogd.service"
vmen: "sudo systemctl enable libvirtd.service qemu-kvm.service virtlockd.service virtlogd.service"
vmdis: "sudo systemctl disable libvirtd.service qemu-kvm.service virtlockd.service virtlogd.service"

ktheme: "kitty + kitten themes"
gtheme: "ghostty +list-themes"

voff: "sudo wg-quick down wg1 && sudo resolvconf -u"
von: "sudo resolvconf -u && sudo wg-quick up wg1"
