###
# Description:
# - Define bash session Aliases in yaml key/value format
# - These will be loaded into your bash session via ./init/load_aliases.sh
###

grabpage: 'wget -p -k -E -H'

bot: "ollama run $ACTIVE_BOT"
bat: "bat -p"
cat: "bat -p"
# fzf: "fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
b: ${BROWSER}
e: nvim --listen /tmp/nvimsocket
eg: "neovide"
r: "source ~/.bashrc"
ff: "fastfetch"

lsd: "lsd --hyperlink=auto"
ls: "lsd"
l: "ls"
ll: "ls -la"

lgit: lazygit
ldocker: lazydocker
ljournal: lazyjournal
lsql: lazysql

allow: "sudo chmod +x"
own: "sudo chown"

yt: "invidious_instance='https://vid.puffyan.us' ytfzf -t"
vmon: 'sudo systemctl start virtqemud.socket virtstoraged.socket virtnetworkd.socket virtlogd.socket virtlockd.socket'
vmoff: 'sudo systemctl stop virtqemud.socket virtstoraged.socket virtnetworkd.socket virtlogd.socket virtlockd.socket'

# vmon:  "sudo systemctl start libvirtd.socket virtqemud.socket virtlogd.socket virtlockd.socket"
# vmoff: "sudo systemctl stop  libvirtd.socket virtqemud.socket virtlogd.socket virtlockd.socket"
vmen:  "sudo systemctl enable libvirtd.socket virtqemud.socket virtlogd.socket virtlockd.socket"
vmdis: "sudo systemctl disable libvirtd.socket virtqemud.socket virtlogd.socket virtlockd.socket"
vmstat: "systemctl status libvirtd.socket virtqemud.socket virtlogd.socket virtlockd.socket --no-pager"
ktheme: "kitty + kitten themes"
gtheme: "ghostty +list-themes"

voff: "sudo wg-quick down work && sudo resolvconf -u"
von: "sudo resolvconf -u && sudo wg-quick up work"

tree: "ls -a --tree ./cwatch/"
