###
# Description:
# - You can define env vars as yaml key value pairs
# - They will be auto loaded into your bash session by load_env.sh
###

ACTIVE_BOT: phi4:latest
SSH_AUTH_SOCK: ${HOME}/.bitwarden-ssh-agent.sock
EDITOR: neovide
MANPAGER: page
PAGER: page
BROWSER: "zen-browser --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer"
BANNER_DISABLED: true
BLOG_DISABLED: true
THEME: "catppuccin_mocha"
THEME_DIR: ${HOME}/.cache/oh-my-posh/themes
BAT_THEME: "Catppuccin Mocha"
FZF_DEFAULT_OPTS: "--no-height --no-reverse --color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 --color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC --color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 --color=selected-bg:#45475A --color=border:#313244,label:#CDD6F4"
FZF_ALT_C_OPTS: "--preview 'tree -C {} | head -200'"
FZF_CTRL_T_OPTS: "--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"

